//
//  Product.swift
//
//  File Generated by vicentesiis on 11/20/2018.
//  Using model_gen.py
//

import ObjectMapper

class Product: Mappable {

	var _id: String!
	var name: String!
	var quantity: Int!

	init() {}

	required init?(map: Map){}

	func mapping(map: Map) {
		_id <- map["_id"]
		name <- map["name"]
		quantity <- map["quantity"]
	}
}

class ProductObject: Mappable {
    
    var product: Product!
    
    init() {}
    
    required init?(map: Map){}
    
    func mapping(map: Map) {
        product <- map["product"]
    }
    
}
